---
- name: Install and configure FreeIPA IdM Server
  hosts: idm_servers
  become: true
  gather_facts: true

  roles:
    - configure_idm_server



  handlers:
    - name: Restart chronyd
      ansible.builtin.systemd:
        name: chronyd
        state: restarted
        enabled: true